apiVersion: v1
kind: ReplicationController
metadata:
  name: "{{ .Release.Name }}-stolon-proxy"
spec:
  replicas: 2
  selector:
    name: "{{ .Release.Name }}-stolon-proxy"
  template:
    metadata:
      labels:
        name: "{{ .Release.Name }}-stolon-proxy"
        stolon-cluster: "{{ .Release.Name }}-kube-stolon"
        stolon-proxy: "true"
    spec:
      containers:
      - name: "{{ .Release.Name }}-stolon-proxy"
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-proxy
        env:
          - name: STPROXY_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "{{ .Release.Name }}-kube-stolon"
          - name: STPROXY_STORE_BACKEND
            value: "{{ .Values.store.backend }}"
          - name: STPROXY_STORE_ENDPOINTS
            value: "{{ .Values.store.endpoints }}"
          - name: STPROXY_LISTEN_ADDRESS
            value: "0.0.0.0"
          ## Uncomment this to enable debug logs
          #- name: STPROXY_DEBUG
          #  value: "true"
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 5
