apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-stolon-keeper"
spec:
  serviceName: "{{ .Release.Name }}-stolon-keeper"
  replicas: 2
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-stolon-keeper"
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: "{{ .Release.Name }}-stolon-keeper"
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            # Generate our keeper uid using the pod index
            IFS='-' read -ra ADDR <<< "$(hostname)"
            export STKEEPER_UID="keeper${ADDR[-1]}"
            export POD_IP=$(hostname -i)
            export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
            export STOLON_DATA=/stolon-data
            chown stolon:stolon $STOLON_DATA
            exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
        env:
          - name: STKEEPER_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "{{ .Release.Name }}-kube-stolon"
          - name: STKEEPER_STORE_BACKEND
            value: "{{ .Values.store.backend }}"
          - name: STKEEPER_STORE_ENDPOINTS
            value: "{{ .Values.store.endpoints }}"
          - name: STKEEPER_PG_REPL_USERNAME
            value: "repluser"
            # Or use a password file like in the below supersuser password
          - name: STKEEPER_PG_REPL_PASSWORD
            value: "replpassword"
          - name: STKEEPER_PG_SU_USERNAME
            value: "stolon"
          - name: STKEEPER_PG_SU_PASSWORDFILE
            value: "/etc/secrets/stolon/password"
          # Uncomment this to enable debug logs
          - name: STKEEPER_DEBUG
            value: "true"
        ports:
          - containerPort: 5432
        volumeMounts:
        - mountPath: /stolon-data
          name: data
        - mountPath: /etc/secrets/stolon
          name: stolon
      volumes:
        - name: stolon
          secret:
            secretName: "{{ .Release.Name }}-stolon"
  # Define your own volumeClaimTemplate. This example uses dynamic PV provisioning with a storage class named "standard" (so it will works by default with minikube)
  # In production you should use your own defined storage-class and configure your persistent volumes (statically or dynamically using a provisioner, see related k8s doc).
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: generic
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: generic
      resources:
        requests:
          storage: 2048Mi
