apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-stolon-proxy-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Release.Name }}-stolon-proxy-service"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stolon-proxy: "true"
    stolon-cluster: "{{ .Release.Name }}-kube-stolon"
