apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-stolon"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Release.Name }}-stolon"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  stolon_initial_clusterfile: |
    {
      "initMode": "new",
      "pgParameters": {
        "max_connections": "300",
        "shared_preload_libraries": "pg_stat_statements.so",
        "archive_mode": "on",
        "archive_command": "/bin/true"
      }
    }
