- name: put values
  template: src=values.yml dest=/tmp/stolon-{{ stolon_helm_release }}.yml

- name: upgrade {{ stolon_helm_release }} release using a Helm chart
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf && helm upgrade {{ stolon_helm_release }} stable/stolon --install --namespace {{ k8s_namespace }} -f /tmp/stolon-{{ stolon_helm_release }}.yml
