kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-2
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/pvs/stolon-cluster-pv-2"
